name: open_mail_app
description: This library provides the ability to query the device for installed
  email apps and open those apps
version: 0.4.4
homepage: https://github.com/HomeXLabs/open-mail-app-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.4
  url_launcher: ^6.2.4
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.homex.open_mail_app
        pluginClass: OpenMailAppPlugin
      ios:
        pluginClass: OpenMailAppPlugin
